name: Generate HTML via Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install pandoc-citeproc
      
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --mathjax
            --bibliography=literature.bib
            --number-sections
            --css main.css
            --filter pandoc-crossref 
            --filter pandoc_filter.py
            --citeproc
            --variable lang=en
            --output main.html 
            --standalone
            main.tex  

      - uses: actions/upload-artifact@v3
        with:
          name: main.html
