name: Generate HTML via Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run pandoc
        run: |
          wget -q https://github.com/jgm/pandoc/releases/download/3.1.11.1/pandoc-3.1.11.1-1-amd64.deb
          sudo dpkg -i pandoc-3.1.11.1-1-amd64.deb
          wget -q https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.17.0c/pandoc-crossref-Linux.tar.xz
          tar -xvf pandoc-crossref-Linux.tar.xz
          sudo mv pandoc-crossref /usr/local/bin/pandoc-crossref
          sudo apt install pandoc-citeproc 
          pip install pandocfilters
          sudo chmod +x pandoc_filter.py
          pandoc --mathjax --bibliography=literature.bib --number-sections --css main.css --filter pandoc-crossref --filter pandoc_filter.py --citeproc --variable lang=en --output main.html --standalone main.tex  

      - uses: actions/upload-artifact@v3
        with:
          name: HTML
          path: main.html
